### ISSUE TITLE
Validation feature

### ISSUE THREAD

**Issue by chilijung** [CannerCMS/cannercms#34]
Validating fields is really important.
In Prisma (GraphQL) the data is strictly defined in DSL. Such as name must be a string `String!`, many fields must have values.  This will cause errors in database and graphQL and crashing the graphQL server.

I think we should add validation feature in Canner soon.

**Comment by abz53378** [comment]
## Usage
In canner-script we should support property `validation`, contains validation rules such as `required, maximum, minimum, pattern , format`, etc.
```js
<string validation={{
  formats: 'url',
  maxLength: 32,
  required: true
}} />
```

And the `required` can be used as a property alone like below because it's used frequently.
```js
<string required validation={{...otherValidation}} />
```

## Validation rules

In first version of validation, we will support the rules of  `string`, `number` and `required`.

- for strings - maxLength, minLength, pattern, format
- for numbers - maximum, minimum, exclusiveMaximum, exclusiveMinimum, multipleOf
- required

## Implementation

- validation library - [ajv](https://github.com/epoberezkin/ajv#validation-keywords)
- validation UI - Show the message at the bottom of component.
- valuation HOC - Call `onDeploy` method in constructor to register a function which will be executed when the deploy function is called so we can get the value and validate it, if it's invalid the deploy action will be terminated.
